version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xpediapart-scrapers
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/xpediapart
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: xpediapart-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 